# Generated by Django 5.2.8 on 2025-11-08 23:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prenume')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nume')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresă email')),
                ('numar_telefon', models.CharField(blank=True, max_length=15, verbose_name='Număr de telefon')),
                ('rol', models.CharField(choices=[('ELEV', 'Elev'), ('PROFESOR', 'Profesor')], default='ELEV', max_length=10, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lectie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_studiu', models.IntegerField(choices=[(9, 'Clasa a 9-a'), (10, 'Clasa a 10-a'), (11, 'Clasa a 11-a'), (12, 'Clasa a 12-a')], verbose_name='An de studiu')),
                ('titlu', models.CharField(max_length=255, verbose_name='Titlu Lecție')),
                ('descriere_scurta', models.TextField(blank=True, verbose_name='Sumar Lecție')),
                ('data_crearii', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lecție',
                'verbose_name_plural': 'Lecții',
                'ordering': ['materie', 'an_studiu', 'titlu'],
            },
        ),
        migrations.CreateModel(
            name='Materie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True, verbose_name='Nume Materie')),
            ],
            options={
                'verbose_name': 'Materie',
                'verbose_name_plural': 'Materii',
                'ordering': ['nume'],
            },
        ),
        migrations.CreateModel(
            name='ElevProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='elev_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('an_studiu', models.IntegerField(choices=[(9, 'Clasa a 9-a'), (10, 'Clasa a 10-a'), (11, 'Clasa a 11-a'), (12, 'Clasa a 12-a')], verbose_name='An de studiu')),
                ('clasa_litera', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, verbose_name='Litera clasei')),
                ('cod_quiz', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDidactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255, verbose_name='Titlu Material')),
                ('descriere', models.TextField(blank=True, verbose_name='Descriere / Conținut text')),
                ('fisier', models.FileField(blank=True, null=True, upload_to='materiale_didactice/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fișier atașat (doar PDF)')),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(limit_choices_to={'rol': 'PROFESOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiale_create', to=settings.AUTH_USER_MODEL)),
                ('lectie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiale', to='main.lectie')),
            ],
            options={
                'verbose_name': 'Material Didactic',
                'verbose_name_plural': 'Materiale Didactice',
                'ordering': ['lectie', 'titlu'],
            },
        ),
        migrations.AddField(
            model_name='lectie',
            name='materie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectii', to='main.materie'),
        ),
        migrations.CreateModel(
            name='ProfesorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profesor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('materie_predata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.materie', verbose_name='Materia predată')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lectie',
            unique_together={('materie', 'an_studiu', 'titlu')},
        ),
    ]
