# Generated by Django 5.2.8 on 2025-11-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevprofile',
            name='cod_quiz',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
