# Generated by Django 5.2.8 on 2025-11-08 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True, verbose_name='Nume Materie')),
            ],
            options={
                'verbose_name': 'Materie',
                'verbose_name_plural': 'Materii',
                'ordering': ['nume'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDidactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_studiu', models.IntegerField(choices=[(9, 'Clasa a 9-a'), (10, 'Clasa a 10-a'), (11, 'Clasa a 11-a'), (12, 'Clasa a 12-a')], verbose_name='An de studiu')),
                ('titlu', models.CharField(max_length=255, verbose_name='Titlu')),
                ('descriere', models.TextField(blank=True, verbose_name='Descriere / Conținut text')),
                ('fisier', models.FileField(blank=True, null=True, upload_to='materiale_didactice/%Y/%m/', verbose_name='Fișier atașat')),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(limit_choices_to={'rol': 'PROFESOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiale_create', to=settings.AUTH_USER_MODEL)),
                ('materie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiale', to='main.materie')),
            ],
            options={
                'verbose_name': 'Material Didactic',
                'verbose_name_plural': 'Materiale Didactice',
                'ordering': ['materie', 'an_studiu', 'titlu'],
            },
        ),
        migrations.AlterField(
            model_name='profesorprofile',
            name='materie_predata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.materie', verbose_name='Materia predată'),
        ),
    ]
