# Generated by Django 5.2.8 on 2025-11-09 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevprofile',
            name='cod_quiz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continut', models.TextField(verbose_name='Conținutul mesajului')),
                ('data_trimitere', models.DateTimeField(auto_now_add=True)),
                ('citit', models.BooleanField(default=False)),
                ('destinatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesaje_primite', to=settings.AUTH_USER_MODEL, verbose_name='Destinatar')),
                ('expeditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesaje_trimise', to=settings.AUTH_USER_MODEL, verbose_name='Expeditor')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesaje',
                'ordering': ['data_trimitere'],
            },
        ),
    ]
