# Generated by Django 5.2.8 on 2025-11-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_elevprofile_cod_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevprofile',
            name='cod_quiz',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
