# Generated by Django 5.2.8 on 2025-11-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_elevprofile_cod_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevprofile',
            name='cod_quiz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
