# Generated by Django 5.2.8 on 2025-11-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_elevprofile_cod_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevprofile',
            name='poza_profil',
            field=models.ImageField(blank=True, null=True, upload_to='poze_profil/'),
        ),
    ]
